name: Code test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install MultiNest
        run: |
          DEPS_DIR="${GITHUB_WORKSPACE}/deps"
          mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
          git clone https://github.com/JohannesBuchner/MultiNest.git
          cd ${DEPS_DIR}/MultiNest/build && cmake .. && make && cd ${GITHUB_WORKSPACE}
          export LD_LIBRARY_PATH=${DEPS_DIR}/MultiNest/lib:${LD_LIBRARY_PATH}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython scipy numpy matplotlib future pytest ipython
      
      - name: Install OMpy
        run: pip install -e .

      - name: List versions
        run: ipython check_env.py

      - name: Test with pytest
        run: pytest ./tests/
